[profile.default]
auto_detect_solc = false
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
cbor_metadata = false
fuzz = { runs = 1_000 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
out = "out"
script = "script"
solc = "0.8.19"
src = "src"
test = "test"

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
arbitrum = { key = "${API_KEY_ARBISCAN}" }
optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
base = { key = "${API_KEY_BASESCAN}" }
sepolia = { key = "${API_KEY_ETHERSCAN}" }
gnosis = { key = "${API_KEY_GNOSISSCAN}", url = "https://api.gnosisscan.io/api/" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
localhost = "http://localhost:8545"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
base = "https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
gnosis = "https://rpc.gnosis.gateway.fm"
